version: "3.7"

services:
  eureka:
    image: eureka-sample:220208
    ports:
      - "8762:8761"
    networks:
      - aw-sample
    healthcheck:
      test: curl -f http://localhost:8761
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9412:9411"
    networks:
      - aw-sample
  api-gateway:
    image: api-gateway:220208
    ports:
      - "8088:8088"
    environment:
      EUREKA_ENDPOINT: http://eureka:8761/eureka
      ZIPKIN_ENDPOINT: http://zipkin:9411
    depends_on:
      - eureka
      - zipkin
    networks:
      - aw-sample
  api1:
    image: api-sample:220208
    environment:
      SERVICE_NAME: service1
      EUREKA_ENDPOINT: http://eureka:8761/eureka
      ZIPKIN_ENDPOINT: http://zipkin:9411
    depends_on:
      - eureka
      - zipkin
    networks:
      - aw-sample
  api2:
    image: api-sample:220208
    environment:
      SERVICE_NAME: service2
      EUREKA_ENDPOINT: http://eureka:8761/eureka
      ZIPKIN_ENDPOINT: http://zipkin:9411
    depends_on:
      - eureka
      - zipkin
    networks:
      - aw-sample


networks:
  aw-sample:
    driver: bridge